//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARKanyFryzjerstwa.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ARKanyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ARKanyResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARKanyFryzjerstwa.Resources.ARKanyResources", typeof(ARKanyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj konto pracownika.
        /// </summary>
        public static string AddEmployeeAccount {
            get {
                return ResourceManager.GetString("AddEmployeeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie utworzono konto dla pracownika..
        /// </summary>
        public static string AddingEmployeeSuccessMsg {
            get {
                return ResourceManager.GetString("AddingEmployeeSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Klient anonimowy.
        /// </summary>
        public static string AnonymousClientName {
            get {
                return ResourceManager.GetString("AnonymousClientName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień kolor.
        /// </summary>
        public static string ChangeColor {
            get {
                return ResourceManager.GetString("ChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmiana hasła zakończyła się niepowodzeniem. Upewnij się, że poprawnie wprowadziłeś dane..
        /// </summary>
        public static string ChangingPasswordErrorMsg {
            get {
                return ResourceManager.GetString("ChangingPasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmiana hasła zakończona sukcesem..
        /// </summary>
        public static string ChangingPasswordSuccessMsg {
            get {
                return ResourceManager.GetString("ChangingPasswordSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamknij.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powtórz nowe hasło.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;h3&gt;Witaj {0} {1}!&lt;/h3&gt;
        ///&lt;p&gt;W aplikacji &lt;a href=&quot;{2}&quot;&gt;ARKany Fryzjerstwa&lt;/a&gt; zostało utworzone dla Ciebie konto. &lt;/p&gt;
        ///&lt;p&gt;Twoje dane:&lt;/p&gt;
        ///&lt;div style=&quot;width: fit-content;border-radius: 10px;background-color: #ddd;margin:5px auto;padding:15px;font-size: 18px;&quot;&gt;
        ///&lt;b&gt;Email:&lt;/b&gt; {3}&lt;br&gt;
        ///&lt;b&gt;Login:&lt;/b&gt; {4}
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;Aby ustawić hasło i móc korzystać z konta należy przejść proces zresetowania hasła dostępny pod adresem &lt;a href=&quot;{5}&quot;&gt;{5}&lt;/a&gt;.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;W razie problemów pozostajemy do dyspozycji.&lt;/p&gt;
        /// [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string CreationEmployeeAccountMailBody {
            get {
                return ResourceManager.GetString("CreationEmployeeAccountMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ARKany Fryzjerstwa - Nowe konto.
        /// </summary>
        public static string CreationEmployeeAccountMailSubject {
            get {
                return ResourceManager.GetString("CreationEmployeeAccountMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu • Pole wymagane
        ///• Format adresu email.
        /// </summary>
        public static string EmailHintText {
            get {
                return ResourceManager.GetString("EmailHintText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pracownicy.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Imię.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się poprawnie załadować listy wszystkich pracowników..
        /// </summary>
        public static string GetAllEmployeesErrorMsg {
            get {
                return ResourceManager.GetString("GetAllEmployeesErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uzupełnij wymagane dane..
        /// </summary>
        public static string IncompleteDataWarningMsg {
            get {
                return ResourceManager.GetString("IncompleteDataWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Informacja.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uzupełnij poprawnie dane..
        /// </summary>
        public static string InvalidFormErrorMsg {
            get {
                return ResourceManager.GetString("InvalidFormErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niepoprawny kod weryfikacyjny..
        /// </summary>
        public static string InvalidVerificationCodeErrorDescription {
            get {
                return ResourceManager.GetString("InvalidVerificationCodeErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwisko.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika / Email.
        /// </summary>
        public static string LoginInputLabel {
            get {
                return ResourceManager.GetString("LoginInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu • Pole wymagane
        ///• Min. 3 znaki
        ///• Może zawierać tylko litery.
        /// </summary>
        public static string NameHintText {
            get {
                return ResourceManager.GetString("NameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowe hasło.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odmowa dostępu. Nie posiadasz odpowiednich uprawnień..
        /// </summary>
        public static string NoPerrmisionErrorMessage {
            get {
                return ResourceManager.GetString("NoPerrmisionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie pamiętasz hasła?.
        /// </summary>
        public static string PasswordResetLink {
            get {
                return ResourceManager.GetString("PasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;h3&gt;Witaj {0} {1}!&lt;/h3&gt;
        ///&lt;p&gt;Otrzymaliśmy prośbę o zresetowanie hasła do Twojego konta w aplikacji ARKany Fryzjerstwa. &lt;/p&gt;
        ///&lt;p&gt;Twój kod weryfikacyjny to:&lt;/p&gt;
        ///&lt;div style=&quot;width: fit-content;text-align: center;letter-spacing: 5px;border-radius: 40px;background-color: #ddd;margin:5px auto;padding:15px;font-size: 26px;&quot;&gt;
        ///&lt;span&gt;&lt;b&gt;{2}&lt;/b&gt;&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;Kod jest ważny do {3}.&lt;/p&gt;
        ///&lt;p&gt;Hasło zresetujesz pod adresem &lt;a href=&quot;{4}&quot;&gt;{4}&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;W razie problemów pozostajemy do dyspozycji.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string ResetPasswordVerificationCodeMailBody {
            get {
                return ResourceManager.GetString("ResetPasswordVerificationCodeMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ARKany Fryzjerstwa - kod weryfkacyjny.
        /// </summary>
        public static string ResetPasswordVerificationCodeMailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordVerificationCodeMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Salon.
        /// </summary>
        public static string Salon {
            get {
                return ResourceManager.GetString("Salon", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zarejestrować salonu. Upewnij się, że poprawnie wypełniłeś formularz i spróbuj ponownie..
        /// </summary>
        public static string SalonRegisterErrorMsg {
            get {
                return ResourceManager.GetString("SalonRegisterErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj swój salon.
        /// </summary>
        public static string SalonRegisterLink {
            get {
                return ResourceManager.GetString("SalonRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie zarejestrowano salon. Zaloguj się używając podanego adresu e-mail i hasła..
        /// </summary>
        public static string SalonRegisterSuccessMsg {
            get {
                return ResourceManager.GetString("SalonRegisterSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zaaktualizować się koloru pracownika..
        /// </summary>
        public static string SavingEmployeeColorErrorMsg {
            get {
                return ResourceManager.GetString("SavingEmployeeColorErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kolor pracownika został pomyślnie zaaktualizowany.
        /// </summary>
        public static string SavingEmployeeColorSuccessMsg {
            get {
                return ResourceManager.GetString("SavingEmployeeColorSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz zasób, który chcesz przypisać do usługi.
        ///Zostanie on dodany do listy poniżej..
        /// </summary>
        public static string ServiceResourcesAssigmentSelectInfo {
            get {
                return ResourceManager.GetString("ServiceResourcesAssigmentSelectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sukces.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił nieznany błąd..
        /// </summary>
        public static string UnknowErrorMsg {
            get {
                return ResourceManager.GetString("UnknowErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono użytkownika o podanych danych..
        /// </summary>
        public static string UserNotFoundErrorMsg {
            get {
                return ResourceManager.GetString("UserNotFoundErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod weryfikacyjny.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do zmiany hasła wymagane jest podanie kodu weryfikacyjnego wysłanego na adres e-mail..
        /// </summary>
        public static string VerificationCodeInfo {
            get {
                return ResourceManager.GetString("VerificationCodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod weryfikacyjny został pomyślnie wysłany na adres e-mail powiązany z kontem..
        /// </summary>
        public static string VerificationCodeSendedMsg {
            get {
                return ResourceManager.GetString("VerificationCodeSendedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostrzeżenie.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nieporawny format przekazanego koloru..
        /// </summary>
        public static string WrongHexColorFormatExceptionMessage {
            get {
                return ResourceManager.GetString("WrongHexColorFormatExceptionMessage", resourceCulture);
            }
        }
    }
}
